const prisma = require('../utils/prisma');
const sla = { CRITICAL: [1, 4], HIGH: [4, 12], MEDIUM: [8, 24], LOW: [24, 72] };
const visibleWhere = user => user.role === 'HQ_ADMIN' ? {} : user.role === 'BRANCH_MANAGER' ? { branchId: user.branchId } : { requesterId: user.id };
const include = { branch: true, requester: { select: { id: true, name: true, email: true } }, assignee: { select: { id: true, name: true, email: true } }, comments: { include: { author: { select: { name: true, role: true } } }, orderBy: { createdAt: 'asc' } } };
const ref = () => `ENG-${Date.now().toString().slice(-7)}`;

exports.dashboard = async (req, res, next) => { try {
  const where = visibleWhere(req.user); const tickets = await prisma.ticket.findMany({ where, select: { status: true, priority: true, resolutionDueAt: true, createdAt: true, branchId: true } }); const now = new Date();
  res.json({ total: tickets.length, open: tickets.filter(t => !['RESOLVED', 'CLOSED'].includes(t.status)).length, critical: tickets.filter(t => t.priority === 'CRITICAL' && !['RESOLVED', 'CLOSED'].includes(t.status)).length, overdue: tickets.filter(t => t.resolutionDueAt < now && !['RESOLVED', 'CLOSED'].includes(t.status)).length, byStatus: Object.fromEntries(['NEW','ACKNOWLEDGED','IN_PROGRESS','WAITING','RESOLVED','CLOSED'].map(k => [k, tickets.filter(t => t.status === k).length])), branches: req.user.role === 'HQ_ADMIN' ? await prisma.branch.findMany({ include: { _count: { select: { tickets: true } } } }) : [] });
} catch (e) { next(e); } };
exports.list = async (req, res, next) => { try { const where = visibleWhere(req.user); if (req.query.status) where.status = req.query.status; if (req.query.priority) where.priority = req.query.priority; const tickets = await prisma.ticket.findMany({ where, include, orderBy: [{ resolutionDueAt: 'asc' }, { createdAt: 'desc' }] }); res.json(req.user.role === 'STAFF' ? tickets.map(ticket => ({ ...ticket, comments: ticket.comments.filter(comment => !comment.internal) })) : tickets); } catch (e) { next(e); } };
exports.create = async (req, res, next) => { try { const { title, description, category, priority = 'MEDIUM' } = req.body; if (!title || !description || !category || !sla[priority]) return res.status(400).json({ message: 'Title, description, category and valid priority are required' }); if (!req.user.branchId) return res.status(400).json({ message: 'HQ users cannot submit branch tickets' }); const [respond, resolve] = sla[priority]; const ticket = await prisma.ticket.create({ data: { reference: ref(), title: title.trim(), description: description.trim(), category: category.trim(), priority, branchId: req.user.branchId, requesterId: req.user.id, responseDueAt: new Date(Date.now() + respond * 3600000), resolutionDueAt: new Date(Date.now() + resolve * 3600000) }, include }); res.status(201).json(ticket); } catch (e) { next(e); } };
exports.update = async (req, res, next) => { try { const ticket = await prisma.ticket.findFirst({ where: { id: req.params.id, ...visibleWhere(req.user) } }); if (!ticket) return res.status(404).json({ message: 'Ticket not found' }); if (req.user.role === 'STAFF') return res.status(403).json({ message: 'Only managers can update ticket workflow' }); const { status, assigneeId } = req.body; const data = {}; if (status && ['NEW','ACKNOWLEDGED','IN_PROGRESS','WAITING','RESOLVED','CLOSED'].includes(status)) { data.status = status; if (status === 'ACKNOWLEDGED' && !ticket.acknowledgedAt) data.acknowledgedAt = new Date(); if (status === 'RESOLVED') data.resolvedAt = new Date(); if (status === 'CLOSED') data.closedAt = new Date(); } if (assigneeId !== undefined) data.assigneeId = assigneeId || null; const updated = await prisma.ticket.update({ where: { id: ticket.id }, data, include }); res.json(updated); } catch (e) { next(e); } };
exports.comment = async (req, res, next) => { try { const ticket = await prisma.ticket.findFirst({ where: { id: req.params.id, ...visibleWhere(req.user) } }); if (!ticket) return res.status(404).json({ message: 'Ticket not found' }); const message = String(req.body.message || '').trim(); if (!message) return res.status(400).json({ message: 'Comment is required' }); const comment = await prisma.ticketComment.create({ data: { ticketId: ticket.id, authorId: req.user.id, message, internal: Boolean(req.body.internal) && req.user.role !== 'STAFF' }, include: { author: { select: { name: true, role: true } } } }); res.status(201).json(comment); } catch (e) { next(e); } };
