import { useEffect, useMemo, useState } from 'react';
import axios from 'axios';
import './App.css';

const api = axios.create({ baseURL: import.meta.env.VITE_API_URL || '' });
const priorities = ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW'];
const statuses = ['NEW', 'ACKNOWLEDGED', 'IN_PROGRESS', 'WAITING', 'RESOLVED', 'CLOSED'];
const label = s => s.replace('_', ' ');
const due = date => { const ms = new Date(date) - Date.now(); const h = Math.abs(Math.round(ms / 3600000)); return ms < 0 ? `${h}h overdue` : `${h}h remaining`; };

function App() {
  const [session, setSession] = useState(() => JSON.parse(localStorage.getItem('ticketSession') || 'null'));
  const [tickets, setTickets] = useState([]), [summary, setSummary] = useState(null), [tab, setTab] = useState('overview'), [selected, setSelected] = useState(null), [message, setMessage] = useState('');
  const headers = session ? { Authorization: `Bearer ${session.token}` } : {};
  const load = async () => { if (!session) return; try { const [t, d] = await Promise.all([api.get('/api/tickets', { headers }), api.get('/api/tickets/dashboard', { headers })]); setTickets(t.data); setSummary(d.data); } catch { localStorage.removeItem('ticketSession'); setSession(null); } };
  useEffect(() => { load(); }, [session]);
  const isManager = session?.user.role !== 'STAFF';
  if (!session) return <Login onLogin={s => { localStorage.setItem('ticketSession', JSON.stringify(s)); setSession(s); }} />;
  const visible = tickets;
  return <main className="shell"><aside><div className="brand"><span>◈</span> ENGINE<span>DESK</span><small>Service management</small></div><nav>{[['overview','Overview'],['tickets','Ticket register'],['new','Raise a ticket']].map(([id, text]) => <button className={tab === id ? 'active' : ''} onClick={() => setTab(id)} key={id}>{text}</button>)}</nav><div className="profile"><b>{session.user.name}</b><small>{session.user.role === 'HQ_ADMIN' ? 'HQ · Company-wide control' : `${label(session.user.role)} · ${session.user.branch?.name || 'HQ'}`}</small><button onClick={() => { localStorage.removeItem('ticketSession'); setSession(null); }}>Sign out</button></div></aside><section className="content"><header><div><p className="eyebrow">Engineering operations</p><h1>{tab === 'overview' ? 'Service control centre' : tab === 'new' ? 'Create a service request' : 'Ticket register'}</h1><p className="sub">{session.user.role === 'STAFF' ? 'Track your requests and SLA commitments.' : session.user.role === 'HQ_ADMIN' ? 'Company-wide view across all engineering branches.' : `Operational view for ${session.user.branch?.name}.`}</p></div><button className="primary" onClick={() => setTab('new')}>+ New ticket</button></header>{message && <div className="notice">{message}</div>}{tab === 'overview' && <Overview summary={summary} tickets={visible} role={session.user.role} setTab={setTab} />}{tab === 'tickets' && <TicketList tickets={visible} manager={isManager} open={setSelected} />}{tab === 'new' && <TicketForm headers={headers} done={(m) => { setMessage(m); setTab('tickets'); load(); }} />}</section>{selected && <TicketModal ticket={selected} manager={isManager} headers={headers} close={() => { setSelected(null); load(); }} />}</main>;
}
function Login({ onLogin }) { const [email, setEmail] = useState('testuser1branch1@test.com'), [password, setPassword] = useState('password123'), [error, setError] = useState(''); const submit = async e => { e.preventDefault(); try { onLogin((await api.post('/api/auth/login', { email, password })).data); } catch (e) { setError(e.response?.data?.message || 'Unable to sign in'); } }; return <div className="login"><form onSubmit={submit}><div className="brand"><span>◈</span> ENGINE<span>DESK</span><small>Engineering service management</small></div><h1>Welcome back</h1><p>Sign in to submit, track, and resolve service requests.</p>{error && <div className="error">{error}</div>}<label>Email<input value={email} onChange={e => setEmail(e.target.value)} /></label><label>Password<input type="password" value={password} onChange={e => setPassword(e.target.value)} /></label><button className="primary">Sign in securely</button><div className="demo"><b>Demo access</b><br/>Staff: testuser1branch1@test.com / password123<br/>Manager: managerbranch1@test.com / admin123<br/>HQ: hq@test.com / admin123</div></form></div> }
function Overview({ summary, tickets, role, setTab }) { if (!summary) return <p>Loading service metrics…</p>; const urgent = tickets.filter(t => !['RESOLVED','CLOSED'].includes(t.status)).slice(0, 5); return <><div className="cards"><Card n={summary.open} t="Open tickets"/><Card n={summary.critical} t="Critical incidents" red/><Card n={summary.overdue} t="SLA attention" amber/><Card n={summary.total} t="Total in scope"/></div><div className="grid"><div className="panel wide"><div className="panelhead"><h2>Priority work queue</h2><button onClick={() => setTab('tickets')}>View register →</button></div>{urgent.length ? urgent.map(t => <TicketRow key={t.id} t={t} />) : <p className="muted">No open tickets.</p>}</div><div className="panel"><h2>Workflow health</h2>{Object.entries(summary.byStatus).filter(([,n]) => n).map(([s,n]) => <div className="metric" key={s}><span>{label(s)}</span><b>{n}</b></div>)}{role === 'HQ_ADMIN' && <><h2 className="space">Branch load</h2>{summary.branches.map(b => <div className="metric" key={b.id}><span>{b.name}</span><b>{b._count.tickets}</b></div>)}</>}</div></div></> }
const Card = ({n,t,red,amber}) => <div className={`card ${red ? 'red' : amber ? 'amber' : ''}`}><b>{n}</b><span>{t}</span></div>;
const TicketRow = ({t, onClick}) => <button className="ticketrow" onClick={onClick}><span className={`dot ${t.priority.toLowerCase()}`}></span><span><b>{t.reference} · {t.title}</b><small>{t.branch?.name} · {t.category}</small></span><span className={`badge ${t.status.toLowerCase()}`}>{label(t.status)}</span><span className={new Date(t.resolutionDueAt) < new Date() ? 'late' : ''}>{due(t.resolutionDueAt)}</span></button>;
function TicketList({ tickets, manager, open }) { const [filter, setFilter] = useState('ALL'); const shown = filter === 'ALL' ? tickets : tickets.filter(t => t.status === filter || t.priority === filter); return <><div className="filters"><button className={filter === 'ALL' ? 'selected' : ''} onClick={() => setFilter('ALL')}>All ({tickets.length})</button>{priorities.map(x => <button key={x} className={filter === x ? 'selected' : ''} onClick={() => setFilter(x)}>{label(x)}</button>)}{statuses.slice(0,4).map(x => <button key={x} className={filter === x ? 'selected' : ''} onClick={() => setFilter(x)}>{label(x)}</button>)}</div><div className="panel table">{shown.map(t => <TicketRow key={t.id} t={t} onClick={() => open(t)} />)}{!shown.length && <p className="muted">No tickets match this filter.</p>}</div></> }
function TicketForm({ headers, done }) { const [form, setForm] = useState({ title:'', category:'Production Equipment', priority:'MEDIUM', description:'' }), [error,setError]=useState(''); const submit=async e=>{e.preventDefault();try { const r=await api.post('/api/tickets',form,{headers});done(`Ticket ${r.data.reference} created and SLA clock started.`)}catch(e){setError(e.response?.data?.message||'Unable to create ticket')}}; return <form className="panel form" onSubmit={submit}>{error&&<div className="error">{error}</div>}<label>Issue title<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="e.g. Compressor vibration alarm"/></label><div className="two"><label>Service category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{['Production Equipment','Facilities','Hydraulic Systems','Electrical','IT Infrastructure','Fleet & Equipment','Quality & Compliance','Health & Safety'].map(x=><option key={x}>{x}</option>)}</select></label><label>Business priority<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}>{priorities.map(x=><option key={x}>{label(x)}</option>)}</select></label></div><label>Problem / concern<textarea required value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Describe the location, impact, current condition, and any immediate safety controls."/></label><div className="sla"><b>SLA / SLG guide</b><span>Critical: acknowledge 1h, resolve 4h · High: 4h / 12h · Medium: 8h / 24h · Low: 24h / 72h</span></div><button className="primary">Submit service request</button></form> }
function TicketModal({ticket, manager, headers, close}) { const [status,setStatus]=useState(ticket.status),[comment,setComment]=useState(''),[busy,setBusy]=useState(false); const save=async()=>{setBusy(true);try{await api.patch(`/api/tickets/${ticket.id}`,{status},{headers});if(comment)await api.post(`/api/tickets/${ticket.id}/comments`,{message:comment},{headers});close()}finally{setBusy(false)}}; return <div className="modalback"><div className="modal"><button className="x" onClick={close}>×</button><p className="eyebrow">{ticket.reference} · {ticket.branch?.name}</p><h2>{ticket.title}</h2><div className="tags"><span className={`badge ${ticket.priority.toLowerCase()}`}>{ticket.priority}</span><span className="badge">{label(ticket.status)}</span><span className={new Date(ticket.resolutionDueAt)<new Date()?'late':''}>Resolution {due(ticket.resolutionDueAt)}</span></div><p>{ticket.description}</p><div className="details"><span>Requester<b>{ticket.requester?.name}</b></span><span>Category<b>{ticket.category}</b></span><span>Created<b>{new Date(ticket.createdAt).toLocaleString()}</b></span></div>{manager&&<label>Workflow status<select value={status} onChange={e=>setStatus(e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select></label>}<label>Add an update<textarea value={comment} onChange={e=>setComment(e.target.value)} placeholder="Add progress, handover, or resolution notes…"/></label><div className="comments">{ticket.comments?.map(c=><p key={c.id}><b>{c.author.name}</b><small>{new Date(c.createdAt).toLocaleString()}</small>{c.message}</p>)}</div><button className="primary" onClick={save} disabled={busy}>{busy?'Saving…':'Save update'}</button></div></div> }
export default App;
